apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
        - name: conversao
          image: kaiodtr/conversao-temperatura:v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: conversao
spec:
  type: LoadBalancer
  selector:
    app: conversao
  ports:
    - name: http
      port: 8087
      targetPort: 8080
      protocol: TCP
